#!/bin/bash

# Download files needed and get current working directory 
cp -r /localdisk/data/BPSM/AY21/fastq .
cp /localdisk/data/BPSM/AY21/Tcongo_genome/TriTrypDB-46_TcongolenseIL3000_2019_Genome.fasta.gz .
cp /localdisk/data/BPSM/AY21/TriTrypDB-46_TcongolenseIL3000_2019.bed .
PATH=$(pwd)

# Use for loop to unzip files in fastq and use fastqc to perform quality check
gunzip TriTrypDB-46_TcongolenseIL3000_2019_Genome.fasta.gz
mkdir qualitycheck.output
for file in $PATH/fastq/*.fq.gz
do
	gunzip $file
	fastqc -o qualitycheck.output $file
done

